# Epimetrics config file
# Last update 9 April 2018

title: EpiMetrics, Inc.
tagline: Health Equity Through Research
description: EpiMetrics, Inc. is a health research institution geared towards the achievement of health equity through rigorous and creative conception, execution, translation, and communication of health systems and policy research.
url: https://epimetrics.com.ph
#url: https://heuristic-heyrovsky-5500cb.netlify.com
baseurl: 

# General Site
collections:
  projects:
    output: true
    # permalink: /projects/:categories/:path/
  events:
    output: false
  photos:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "" # all paths
      type: "posts"
    values:
      layout: "article"
      featured: "false"
      comments: "true"
      is_post: true
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      featured: "false"
      is_post: true

# Google Analytics
google_analytics: UA-115634204-2

plugins:
  - jekyll-sitemap
  - jekyll-target-blank