# Epimetrics config file
# Last update 9 April 2018

title: Epimetrics
tagline: Health Equity Through Research
# description:  ## description of Epimetrics. Can be placed in meta tags.
# url: https://epimetrics.com.ph
# url: https://heuristic-heyrovsky-5500cb.netlify.com
baseurl: 

# General Site
collections:
  projects:
    output: true
    permalink: /projects/:path/
  events:
    output: false
  photos:
    output: false