# Epimetrics config file
# Last update 9 April 2018

title: EpiMetrics, Inc.
tagline: Health Equity Through Research
# description:  ## description of Epimetrics. Can be placed in meta tags.
url: https://epimetrics.com.ph
#url: https://heuristic-heyrovsky-5500cb.netlify.com
baseurl: 

# General Site
collections:
  projects:
    output: true
    # permalink: /projects/:categories/:path/
  events:
    output: false
  photos:
    output: false

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: "" # all paths
      type: "posts"
    values:
      layout: "article"
      featured: "false"
      comments: "true"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
      featured: "false"

# Google Analytics
google_analytics: UA-115634204-2